project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Riya Sharma" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Riya's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: My Work
        menu: 
          - academic.qmd
      - text: Portfolio 
        menu: 
        - text: Articles
          file: articles.qmd
        - text: Distance Learning Story
          file: news.qmd
        - text: Sample Breaking News Story
          file: breaking.qmd
      - text: R Walkthroughs
        menu: 
        - text: Sample Walkthrough
          file: walkthrough.qmd
        - text: Election Project
          file: electionproj.qmd
        - text: Income Inequality Project
          file: tidywalkthrough.qmd
      
      


format:
  html:
    theme: minty
    css: styles.css
    toc: true



