---
title: "Academic Work"
---

## Writing

#### **Objectivity in Journalism: An Analysis of Reporting Racial \[In\]Justice**

*This is a paper I wrote which discusses objectivity in journalism through the lenses of advocacy journalism, campaign journalism, and the purported ideal of scientific objectivity in reporting.*

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

From its start, journalism has significantly developed, becoming more nuanced and expansive as reporters and the public interact together in the production and dissemination of news. For decades, one of journalism's mainstays throughout the coverage of increasingly complex events has been objectivity. For both the newsroom and consumers of news, objectivity has cemented itself as a tenet of journalism and as the foundation of accurate, precise reporting. In recent years and especially in the wake of the 2020 Black Lives Matter protests, this canon within the media has transformed and branched out into various forms, including advocacy journalism, campaign journalism, and the search for scientific-like objectivity. To understand these three, examining discussions by various scholars and the hard, reported news that reflects these different perspectives is necessary. By doing so, readers may be able to further understand existing divisions of objectivity and how they operate in different journalistic spheres.  

##### **ADVOCACY JOURNALISM**

Part of what makes diverse facets of objectivity so fascinating is how they are not always beholden to the traditional ideal of objectivity. Case in point: advocacy journalism. This standard deviates from the traditional norm of impartiality because, in its essence, advocacy journalism is driven by a call for a particular goal and outcome. To accomplish the fulfillment of a specific goal, advocacy requires journalists to "take serious thought and purposeful action" for a cause, as Ida B. Wells emphasized in an effort to mobilize Black journalists to report on lynchings and, as a result, inform citizens and ameliorate racial disparities (Wells "The Requirements of Southern Journalism"). In continuation with Wells's call to action, Black journalists created their own newspapers to adequately educate others on racial issues, specifically those pertaining to Black and African Americans within the United States. In the wake of protests related to racially-motivated attacks and murders of these individuals, such newspapers have used their platform to promote equality, equity, and justice for Black and African American citizens. 

For example, The Los Angeles Sentinel, a weekly-African American newspaper, published two separate articles on events occurring in the summer of 2020. In one piece, the Sentinel News Service used the Los Angeles mayor, Eric Garcetti's, remarks as a vehicle to encourage participation in ongoing protests, stating, "The Mayor's announcement shows us all why we must keep pushing and why Angelenos must keep speaking out and showing up for Black lives. We must keep going until we tear down this wall \[of disinvestment\] completely." (Sentinel News Service "Statement on Mayor Garcetti's Announcements During Ongoing Protests"). In another, Executive Publisher Danny Bakewell, Sr. echoed similar sentiments while simultaneously cautioning readers on the dangers of protesting during the COVID-19 pandemic, saying, "..we cannot now risk destroying our city or our health by engaging in activities which put our community or our lives in jeopardy\...Let's be smart, let's be safe and let's keep the faith and please VOTE, VOTE, VOTE!!" (Bakewell Statement from the Executive Publisher on Death and Protest of George Floyd). 

As illustrated in these excerpts of reported news, these advocacy journalists have redefined objectivity by urging readers to engage in protests and vote while simultaneously reporting on the statistics and other facts that accompany stories. In addition to fulfilling the role of advocates, these journalists help bring together members of the Black/African American community, as ethnic newspapers did in times of crisis. As scholar Leara D. Rhodes described, "Racism prompted the development of ethnic media." (Rhodes 47-48). Just as lynchings prompted Ida B. Wells to pursue advocacy journalism, protests, both past and present, have led to the formation of newspapers, like The Los Angeles Sentinel, that amplify Black/African American voices while encouraging change through connection with consumers. 

Despite serving these functions, advocacy journalism has its limitations. For instance, although they appeal to American citizens, newspapers that prioritize advocacy tend to be of a smaller scale. As a result, they may suffer in their ability to consistently reach and influence policymakers who hold power to enact official reform. Progress through individual citizens holds the risk of being lengthy and more miniscule than high-profile reporters on FOX News or CNN. 

##### **CAMPAIGN JOURNALISM**

In a similar vein as advocacy journalism, the standard of campaign journalism operates within the framework of impartiality. While it shares the goal of advocating attention to a particular problem, campaign journalism does not require journalists to call action towards said problem. As sociologist Rodney Benson described, campaign journalism requires reporters "to focus their energies..on alerting the public to the most important events and issues of the day" instead of "allowing an autocratic-styled president to set the news agenda" (Benson 213). This standard of objectivity and coverage focuses on continued analysis of an issue both the public and the press deem appropriate, like racial justice and related protests. In addition to ongoing broadcasting of these events in the summer of 2020, journalists concentrated on the actions of politicians and political parties in response to racial injustice so they sustain " reporting----and repeating----the truth" (Benson 214). 

Take, for example, New York Times journalist Astead W. Herndon, who analyzed a discrepancy between elected Democrats' actions and public demands for reforming systemic racism in the weeks after the murder of George Floyd. He writes, "activists are saying they're worried that politicians are using the language of systemic reform but stopping short of the more radical policies to address it, such as redirecting funding from law enforcement to housing and education" (Herndon "For George Floyd's Mourners, What Does 'Justice' Mean?"). Instead of simply moving from one beat to the next, Herndon's article engages in sustained coverage of racial justice and reform as it enters the rhetoric of policy-making politicians, specifically those in the Democratic party. 

Similarly, additional New York Times journalists coupled news of activism with the actions of politicians, like current Vice President Kamala Harris. In August 2020, they wrote, "Since becoming California's attorney general in 2011, she had largely avoided intervening in cases involving killings by the police. Protesters in Oakland distributed fliers saying: "Tell California Attorney General Kamala Harris to prosecute killer cops! It's her job!"' (Hakim et al. "'Top Cop' Kamala Harris's Record of Policing the Police"). Characteristic of the tenets of campaign journalism outlined by scholars, such as Benson, these journalists continuously reported on a movement----even in the months after Black Lives Matter and accompanying protests initially swept the nation----because it affects numerous American citizens. Furthermore, by relaying the facts behind Harris's inaction, they provided valuable material to the public so they remained well-informed and educated on a candidate. 

While Herndon and additional journalists prioritized objectivity and impartiality in their reporting of the Democratic party and its politicians, they continued to serve the public by acting as watchdogs. In doing so, these journalists allowed readers to fully understand and develop their thoughts on the bigger issues at hand in the 2020 presidential election and the country as a whole. Despite these benefits, however, campaign journalism becomes limited when this sustained coverage takes away from the dissemination of other, important news. While the public may become well-versed in the activist agendas of certain political figures, their knowledge of additional domains may diminish, resulting in an ill-informed community. 

##### **SCIENTIFIC-LIKE OBJECTIVITY**

While the branches of advocacy and campaign journalism emphasize how journalists may adapt their style of reporting to the dynamic nature of what is being covered, a separate approach----scientific-like objectivity----prioritizes the circulation of undiluted facts to quell misinterpretation. Famed writer Walter Lippmann highlighted this standard and its goal, saying, "I try to indicate that the perplexities of government and industry are conspiring to give political science this enormous opportunity to enrich itself and serve the public" (Lippmann 32).

In contrast with American philosopher John Dewey, who viewed "the role of experts as ancillary to that of citizens," (Dewey and Rogers 30) Lippmann argues that the publication of facts and figures from research centers----rather than citizens----eases confusion created by "pseudo environments," or the perceptions beholden by individuals due to their unique experiences. 

This proliferation of data can be seen even in the light of social, not technological events, like the police brutality that prompted protests across the United States. For instance, The Washington Post instructed journalists to create and contribute to databases that gather statistical information regarding racial groups affected by police brutality. Accompanying these figures are analysis paragraphs by journalists, so the research is not inaccessible to ordinary citizens, curbing one of Dewey\'s fears. One such paragraph explains the inordinate percentage of attacks against Black Americans, stating, \"Although half of the people shot and killed by police are White, [Black Americans are shot at a disproportionate rate](https://www.washingtonpost.com/news/post-nation/wp/2016/07/11/arent-more-white-people-than-black-people-killed-by-police-yes-but-no/). They account for less than 13 percent of the U.S. population, but are killed by police at more than twice the rate of White Americans\" (Tate et al. \"Fatal Force: Police shootings Database\"). Not only do these databases reach the goal of empiricism and visible evidence through graphs that reflect data from research centers, but they also implement links to further reliable sources. The combination of these actions results in the propagation of a factual, impartial standard of objectivity. 

Instead of falling prey to partisanship or misinformation, the professionalization of journalists and the introduction of more scientific data journalism may ward off the infiltration of propaganda within the news. In conjunction with this, data journalism's reliance on certainty reduces the risk that "the news consumer may accuse both the reporter and the news organization of bias," a concern outlined by scholar Gaye Tuchman (Tuchman 665). However, data journalism still brings some limitations, one being alienation from issues. While statistics and other pieces of factual information are useful for visualizing material, they prevent readers from accessing discussions, quotes, and other facets of traditional reporting that allow citizens to understand issues and form opinions on them. 

##### **CONCLUSION**

The approaches of advocacy journalism, campaign journalism, and scientific-like objectivity all offer unique perspectives and advantages to the field of reporting, as exemplified in theoretical and philosophical pieces by scholars and excerpts from published articles. While some argue that one method of writing takes precedence over others, it is clear that all three are equally valuable and necessary in today's society. Advocacy and campaign journalism demonstrate pressing issues directly to readers, with advocacy prompting important social change and campaign promoting literacy on public or political affairs. Offering empirical knowledge, scientific-like objectivity presents direct, factual evidence to citizens so they do not fall prey to misinformation and bias within the media. These approaches play off of each other within articles, like those published during and after racial justice protests, in order to enrich the sphere of journalism and those who consume it. 

##### Works Cited

Bakewell, Danny. "Statement from the Executive Publisher on Death and Protest of George Floyd." Los Angeles Sentinel, Los Angeles Sentinel, 11 June 2020, lasentinel.net/179124.html. 

Benson, Rodney. "The Case for Campaign Journalism." Trump and the Media, by Pablo J. Boczkowski and Zizi Papacharissi, The MIT Press, 2018, pp. 213--214. 

"Chapter Four / Press Functions." The Ethnic Press: Shaping the American Dream, by Leara D Rhodes, P. Lang, 2010, pp. 47--48. 

Dewey, John, and Melvin L. Rogers. "The Public and Its Problems: an Essay in Political Inquiry." The Public and Its Problems: An Essay in Political Inquiry, Swallow Press, 2016, pp. 30--30. 

Hakim, Danny, et al. "'Top Cop' Kamala Harris's Record of Policing the Police." The New York Times, The New York Times, 9 Aug. 2020, www.nytimes.com/2020/08/09/us/politics/kamala-harris-policing.html?searchResultPosition=1. 

Herndon, Astead  W. "For George Floyd's Mourners, What Does 'Justice' Mean?" The New York Times, The New York Times, 12 June 2020, www.nytimes.com/2020/06/12/us/politics/george-floyd-racial-justice.html?searchResultPosition=20. 

Sentinel News Service. "Statement on Mayor Garcetti's Announcements During Ongoing Protests." Los Angeles Sentinel, Los Angeles Sentinel, 4 June 2020, lasentinel.net/statement-on-mayor-garcettis-announcements-during-ongoing-protests.html

Tate, Julie, et al. "Fatal Force: Police Shootings Database." The Washington Post, WP Company, 22 Jan. 2020, www.washingtonpost.com/graphics/investigations/police-shootings-database/. 

"The World Outside and the Pictures in Our Heads." Public Opinion, by Walter Lippmann, CPSIA, 2019, pp. 32--32. 

Tuchman, Gaye. "Objectivity as Strategic Ritual: An Examination of Newsmen's Notions of Objectivity." American Journal of Sociology, vol. 77, no. 4, 1972, pp. 660--679. JSTOR, www.jstor.org/stable/2776752. Accessed 22 Mar. 2021.

Wells, Ida B. The Requirements of Southern Journalism. 16 Jan. 2020, commonreader.wustl.edu/c/the-requirements-of-southern-journalism/.

#### **Standing on a Stalled Escalator: The Impact of Race on the Mobility of Black Americans and African Americans Within the Workplace**

*This is a paper I wrote examining the issue of discrimination in and out of the workplace for Black and African Americans in the US. I presented my findings at the Spring 2021 University Writing and Research Conference.*

*You can read about the conference and my abstract [here](https://writingprogram.gwu.edu/university-writing-research-conference-program-spring-2021).*

You can see my paper [here](https://drive.google.com/file/d/1pOz1F0ECqQ-tPAHgpup-2Oi-XmQ0yyGV/view?usp=sharing).
