---
title: "Long-form News Story"
editor: visual
---

# **Distance Learning Story**

*In my News Writing and Reporting class, I wrote a story about the experience of international students studying during virtual school in the 2020-2021 academic year at GW.*

------------------------------------------------------------------------

## Remote learning proves challenging for international students at The George Washington University

In Dubai, GW freshman Nour Ellahham goes to sleep at 5 a.m. and wakes up at 10 a.m. Gulf Standard Time to attend classes. One and a half hours ahead of her in Hyderabad, Ajay Uppaluri "passes out" after completing schoolwork from 4:30 a.m. to 10 a.m. Indian Standard Time.  

More than a year into the COVID-19 pandemic, students and faculty at GWU are still confronting the challenges of virtual learning. For international students, the pressure of managing work is compounded by studying in sometimes opposite time zones. While they struggle to socialize and submit assignments, international students try to adapt alongside professors who work to accommodate their schedules.

Ellahham, a freshman majoring in political science at GWU, began her first year of college in Dubai instead of Washington, D.C, where the university is located.

"If I could describe my online learning experience in one word, I would definitely say frustrating," Ellahham said.

One of about [4,000](https://irp.gwu.edu/dashboard-enrollment-dashboard) international students at the university, Ellahham restructured her entire schedule to attend five classes a week, all of which are synchronous, or live.

"I don't really have a routine anymore. It's confusing when my brain is in Eastern Standard Time, but my body is in Gulf Standard Time. I never know when I should be working or sleeping," Ellahham said.

International students' challenges go beyond academics. In addition to managing 16 credits this semester, Ellahham has experienced difficulty engaging in student life. Because meetings conflict with her schedule, she has not been able to join GW UNICEF, GW College Democrats, or other organizations she finds interesting.  

"It was really, really hard for me to not join a student org. I wanted to get involved, but I am also trying to get through school on top of balancing a lot of external life responsibilities," Ellahham said.

Uppaluri, a sophomore majoring in political science at GWU, traded campus life for family life after moving back to India from the United States. Although he now lives with his parents, Uppaluri follows Eastern Standard Time to attend synchronous classes, making it hard for him to interact with family daily.

"I'm spending more time with them than before, but it's not as much as I want to," Uppaluri said.

After studying throughout the week, Uppaluri can only visit his grandparents on Saturday and spend time relaxing with his cousins on Sunday. However, because he spends his entire weekend with family, Uppaluri cannot catch up on the sleep he needs to continue pulling all-nighters.

"I don't have balance. I push myself...It's this weird middle ground, which is not fun. I don't enjoy it," Uppaluri said.

Fewer international students are attending U.S. schools because of the pandemic and the challenge of online learning. The enrollment of new international students into U.S. institutions fell 43% from 2019, according to a [survey](https://www.iie.org/Research-and-Insights/Open-Doors/Fall-International-Enrollments-Snapshot-Reports) conducted by the Institute of International Education.

To maintain participation among enrolled international students, professors at GWU have made adjustments to accommodate their unique schedules. While some conduct synchronous lectures, others give international students the option to learn asynchronously, or on their own time.  

Dr. Efrat Nechushtai, an assistant professor in GWU's School of Media and Public Affairs, records live lectures for international students in different time zones to watch asynchronously. To facilitate engagement with course material, Nechushtai requires these students to communicate what they've learned and don't understand in one page.

"I wanted to make sure that the course is flexible and that they \[international students\] have this choice to take and engage with the course in any way that is most suitable for their current situation," Nechushtai said.

In addition to individual course adjustments, professors have access to [FLEX Camp workshops](https://gwtoday.gwu.edu/virtual-teaching-camps-will-help-instructors-transition-distance-and-blended-learning) held by GWU Libraries and Academic Innovation. These two-day boot camps offer professors a comprehensive guide on designing courses for remote teaching. With over 10 workshops in summer and more throughout the year, educators can discover new ways to accommodate international students learning online.

"Any professor at GWU has access to many different kinds of programs to help think about how to make the transition \[to remote teaching\] in the best, most effective way possible," Nechushtai said.

International students praised the accommodations professors have provided.

"I have all of these things to be grateful for. I have great professors who have been trying so hard to make remote learning manageable for me," Ellahham said.

Uppaluri offered advice to other international GWU students learning virtually. "Try to manage your time as much as you can and speak to your professors. They are super understanding and want to help you," Uppaluri said.

